/* tslint:disable */
/* eslint-disable */
/**
 * Config Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ConfigmanagerBulkSetConfigsRequest
 */
export interface ConfigmanagerBulkSetConfigsRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfigmanagerBulkSetConfigsRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {Array<BulkSetConfigsRequestConfig>}
     * @memberof ConfigmanagerBulkSetConfigsRequest
     */
    'configs': Array<BulkSetConfigsRequestConfig>;
}
